# Generated by Django 4.2.3 on 2023-08-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_mobiles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
